### PR TITLE
Number fields default to null instead of empty string

### LINKED ISSUE #33: empty number fields return a string instead of null
In the case that a user gives no default values, the number fields return an empty string instead of a `null` value.

### PR DESCRIPTION
**Pull request by EricSSartorius**
Closes #33

### CODE REVIEW

**Comment by stolinski** [comment]
I've taken a stab at this and have made a `getEmptyValue` function to abstract out some of the nastyness.

**Comment by stolinski** [comment]
I'm going to close in favor of my more dry solution, but it's largely just a reworked version of what you did.

**Comment by EricSSartorius** [comment]
Dope!

**Comment by stolinski** [comment]
Actually, I'm realizing we already have a mechanism built in to handle this, we just have to make Number a special field. I'm re-writing now.

**Comment by EricSSartorius** [comment]
Word

**Comment by stolinski** [comment]
Also number inputs by default output strings. So fixing that too.

**Pull request closed without merging**
